name: CI
on: [pull_request]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false # for some reason, Actions build fails when it tries to use: npm ERR! @commitlint/cli not accessible from tilia-nodejs-sdk 
          working-directory: |
            sdk
            example-server

      - name: create env file
        run: |
          touch sdk/.env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> sdk/.env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> sdk/.env
          echo TEST_BUYER_USD_WALLET_ID=${{ secrets.TEST_BUYER_USD_WALLET_ID }} >> sdk/.env
          echo TEST_BUYER_WITH_PAYMENT_METHODS_ACCOUNT_ID=${{ secrets.TEST_BUYER_WITH_PAYMENT_METHODS_ACCOUNT_ID }} >> sdk/.env
          echo TEST_USER_ACCOUNT_ID=${{ secrets.TEST_USER_ACCOUNT_ID }} >> sdk/.env
          echo TEST_USER_ACCOUNT_USERNAME=${{ secrets.TEST_USER_ACCOUNT_USERNAME }} >> sdk/.env
          cat sdk/.env

      - name: Lint
        run: cd sdk/ && npm run lint

      - name: Test
        run: cd sdk/ && npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run: cd sdk/ && npm run build
